# This file was adapted from idris2-lsp
name: Ubuntu
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - main

env:
  SCHEME: scheme

jobs:
  build-idris2-with-docs:
    runs-on: ubuntu-latest
    env:
      IDRIS2_CG: chez
      IDRIS2_TESTS_CG: chez
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Idris2 commit
        id: get-idris2-commit
        run: "echo idris2-commit=$(git rev-parse @:./Idris2) >> $GITHUB_ENV"
      - name: Cache Idris2 with API
        id: cache-idris2-with-docs
        uses: actions/cache@v2
        with:
          path: ~/.idris2/
          key: ${{ env.idris2-commit }}-idris2-with-docs
      - name: Install build dependencies
        if: steps.cache-idris2-with-docs.outputs.cache-hit != "true"
        run: |
          sudo apt-get install -y chezscheme
          echo "$HOME/.idris2/bin" >> $GITHUB_PATH
      - name: Get Idris2 submodule
        if: steps.cache-idris2-with-docs.outputs.cache-hit != "true"
        run: |
          git submodule update --init Idris2
      - name: Build Idris2 with Docs
        if: steps.cache-idris2-with-docs.outputs.cache-hit != "true"
        working-directory: Idris2
        run: |
          make bootstrap && make install
          # cheat a little here
          # make clean
          # make
          # make install
          make install-libdocs
      - name: Artifact Idris2 with Docs
        uses: actions/upload-artifact@v2
        with:
          name: installed-idris2-with-docs
          path: ~/.idris2
          retention-days: 1
  build:
    runs-on: ubuntu-latest
    needs: build-idris2-with-docs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Idris2 with Docs Artifact
        uses: actions/download-artifact@v2
        with:
          name: installed-idris2-with-docs
          path: ~/.idris2/
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          cache: 'pip'
      - nme: Install html5lib
        run: pip3 install html5lib
      - name: build
        run: |
          python3 idris2dash
          tar zcf Idris2.tgz Idris2.docset
          echo fixme
        shell: bash
      
      - name: Artifact docset
        uses: actions/upload-artifact@v2
        with:
          name: idris2-docset
          path: Idris2.docset
      - name: Artifact docset tgz
        uses: actions/upload-artifact@v2
        with:
          name: idris2-docset-tgz
          path: Idris2.tgz

      
